#!/bin/sh
#
# cppdef
#
# Copyright (c) 2015-2017, Oleksiy Chernyavskyy
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

################################################################################
# JUMP TO MODERN SHELL IF POSSIBLE
(test_exit_code_127_sdfjsdfksjdhfksjdhf  >/dev/null) 2>/dev/null
if test $? -ne 127; then
  if test -z "$CPPDEF_BASH_REDIRECT"; then
    CPPDEF_BASH_REDIRECTED=1
    export CPPDEF_BASH_REDIRECTED
    if test -x /bin/bash; then
      exec /bin/bash "$0" ${1+"$@"}
    elif test -x /usr/bin/bash; then
      exec /usr/bin/bash "$0" ${1+"$@"}
    elif test -x /usr/local/bin/bash; then
      exec /usr/local/bin/bash "$0" ${1+"$@"}
    elif test -x /usr/pkg/bin/bash; then
      exec /usr/pkg/bin/bash "$0" ${1+"$@"}
    else
      (bash -c "pwd" >/dev/null) 2>/dev/null
      if test $? -eq 0; then
        exec bash "$0" ${1+"$@"}
      fi
    fi
  fi
fi
CPPDEF_BASH_REDIRECTED=
export CPPDEF_BASH_REDIRECTED
################################################################################

script_name=`basename "$0"`
test_dir=/tmp/cppdef_$$
version_string="0.9"
c_ext="c"

print_help() {
cat <<EOF
Read CPP defines

Usage: $script_name [options] <defines>...

Options:
 -cmd=<cmd>            specify compiler command
 -cctype=<type>        compiler type: gcc clang mingw ticc msc
 *.h|*.H|*.hpp         header files. Other file extensions are recognized
 -inc=<list>           header files
 -v                    print version
 -*                    compiler flags
 <defines>..           preprocessor defines to read
EOF
}

print_version() {
  echo "cppdef $version_string"
}

clean_exit() {
  ecode=$1
  cd /tmp
  rm -rf $test_dir
  exit $ecode
}

op_cmd=gcc
op_cctype=gcc
op_inc=
op_cflags=
op_def=
while test $# -gt 0; do
  case "$1" in
    -h|-help|--help)
      print_help
      exit 0
      ;;
    -cmd=*)
      op_cmd=`echo "$1" | sed 's/^[^=]*=//'`
      ;;
    -cctype=*)
      op_cctype=`echo "$1" | sed 's/^[^=]*=//'`
      ;;
    -inc=*)
      arg=`echo "$1" | sed 's/^[^=]*=//'`
      op_inc="$op_inc $arg"
      ;;
    -v)
      print_version
      exit 0
      ;;
    -*)
      op_cflags="$op_cflags $1"
      ;;
    *.h)
      op_inc="$op_inc $1"
      ;;
    *.H|*.[Hh]++|*.[Hh][Hh]|*.[Hh][Xx][Xx]|*.[Hh][Pp][Pp])
      op_inc="$op_inc $1"
      ;;
    *)
      op_def="$op_def $1"
      ;;
  esac
  shift
done

cpp_flag=-E
case "$op_cctype" in
  gcc|clang|mingw) : ;;
  ticc)
    cpp_flag=-ppl
    ;;
  msc)
    cpp_flag="/E"
    ;;
  *)
    echo "$script_name: error: invalid compiler type $op_cctype" >&2
    exit 1
    ;;
esac

if test -z "$op_def"; then
  exit 0
fi

rm -rf $test_dir 2>/dev/null
(mkdir $test_dir >/dev/null) 2>/dev/null
if test ! -d $test_dir; then
  echo "$script_name: error: could not create temporary directory $test_dir" >&2
  exit 1
fi
cd $test_dir

################################################################################
# SET UP TEST DIR
test_src_base=test_src_base.$c_ext

echo "" >$test_src_base
for inc in $op_inc; do
  inc=`echo "$inc" | sed 's/[<]//' | sed 's/[>]//'`
  echo "#include <$inc>" >> $test_src_base
done

test_src=test_src.$c_ext
test_pp=test_src.pp

################################################################################
# READ DEFINES
defvals=
for def in $op_def; do
  cat $test_src_base > $test_src

  cat <<EOF >>$test_src
#ifdef $def
CPPDEF_DEFVAL=$def
#endif
EOF
  if test "$op_cctype" = ticc; then
    $op_cmd $op_cflags $cpp_flag $test_src 2>/dev/null
    if test $? != 0; then
      echo "$script_name: CPP error" >&2
      clean_exit 1
    fi
    cat $test_pp > test_c.out
    rm -f $test_pp
  else
    $op_cmd $op_cflags $cpp_flag $test_src 2>/dev/null > test_c.out
    if test $? != 0; then
      echo "$script_name: CPP error" >&2
      clean_exit 1
    fi
  fi

  defval=`cat test_c.out | grep "^ *CPPDEF_DEFVAL" | sed 's/^ *CPPDEF_DEFVAL=//' | sed 's/ *$//' | sed 's/"$//' |  sed 's/^"//' | tr -d '\n'`
  if test -n "$defval"; then
    if test -n "$defvals"; then
      defvals="$defvals $defval"
    else
      defvals=$defval
    fi
  fi
done

echo "$defvals" | sed 's/^ *//'
clean_exit 0

